Repository notch8/iiif_print, pull requests merged in 2023-11, with the labels that each got.

#281 Loosen up rails restriction
  iiif_print.gemspec
Labels: patch-ver

#283 🎁 Add graceful fallback of preprocessing
  lib/iiif_print/errors.rb
  lib/iiif_print/split_pdfs/derivative_rodeo_splitter.rb
  spec/iiif_print/split_pdfs/derivative_rodeo_splitter_spec.rb
Labels: patch-ver

#284 make target count part of the error message for children
  lib/iiif_print/jobs/create_relationships_job.rb
Labels: patch-ver

#288 :gift: IiifPrint Enhancements to clean up split works as PDF fileset is deleted
  app/actors/iiif_print/actors/cleanup_file_sets_actor_decorator.rb
  app/actors/iiif_print/actors/file_set_actor_decorator.rb
  app/indexers/concerns/iiif_print/child_indexer.rb
  app/models/concerns/iiif_print/set_child_flag.rb
  app/models/concerns/iiif_print/solr/document.rb
  app/models/iiif_print/pending_relationship.rb
  db/migrate/20231110163052_add_model_details_to_iiif_print_pending_relationships.rb
  lib/iiif_print.rb
  lib/iiif_print/engine.rb
  lib/iiif_print/jobs/child_works_from_pdf_job.rb
  lib/iiif_print/jobs/create_relationships_job.rb
  lib/iiif_print/split_pdfs/destroy_pdf_child_works_service.rb
  spec/iiif_print/jobs/create_relationships_job_spec.rb
  spec/iiif_print/split_pdfs/destroy_pdf_child_works_service_spec.rb
Labels: patch-ver

#286 🧹 Add Solargraph as dependency
  .solargraph.yml
  iiif_print.gemspec
Labels: patch-ver

#285 🐛 Leverage CopyGenerator to ensure we have local copy
  app/services/iiif_print/derivative_rodeo_service.rb
  lib/iiif_print/split_pdfs/base_splitter.rb
  lib/iiif_print/split_pdfs/derivative_rodeo_splitter.rb
  spec/iiif_print/split_pdfs/derivative_rodeo_splitter_spec.rb
Labels: patch-ver

#290 Create Child Works based on PDF fileset's file
  app/actors/iiif_print/actors/file_set_actor_decorator.rb
  lib/iiif_print/split_pdfs/child_work_creation_from_pdf_service.rb
Labels: bug, patch-ver

#293 🧹 Fix broken specs
  app/actors/iiif_print/actors/file_set_actor_decorator.rb
  spec/iiif_print/split_pdfs/derivative_rodeo_splitter_spec.rb
  spec/services/iiif_print/derivative_rodeo_service_spec.rb
Labels: patch-ver

#296 📚 Add documentation regarding DerivativeRodeo
  README.md
  lib/generators/iiif_print/templates/config/initializers/iiif_print.rb
  lib/iiif_print.rb
Labels: patch-ver

#302 I294 add button to resplit work
  app/controllers/iiif_print/split_pdfs_controller.rb
  app/views/hyrax/file_sets/_show_actions.html.erb
  config/locales/iiif_print.en.yml
  config/routes.rb
  lib/generators/iiif_print/install_generator.rb
  lib/iiif_print.rb
  lib/iiif_print/errors.rb
  lib/iiif_print/jobs/request_split_pdf_job.rb
Labels: minor-ver

#303 🐛 Fix install location for helpers/iiif_print_helper
  lib/generators/iiif_print/install_generator.rb
Labels: patch-ver

#305 🐛 Work through fallback of rodeo URLs
  app/services/iiif_print/derivative_rodeo_service.rb
  lib/iiif_print/jobs/child_works_from_pdf_job.rb
  lib/iiif_print/split_pdfs/derivative_rodeo_splitter.rb
  lib/iiif_print/split_pdfs/destroy_pdf_child_works_service.rb
Labels: patch-ver

#306 🎁 Introduce .named_derivatives_and_generators_filter
  README.md
  app/services/iiif_print/derivative_rodeo_service.rb
  lib/iiif_print/errors.rb
  lib/iiif_print/split_pdfs/derivative_rodeo_splitter.rb
Labels: minor-ver
