Repository notch8/iiif_print, pull requests merged in 2023-04, with the labels that each got.

#205 Add `OMP_THREAD_LIMIT=1` to tesseract call
  lib/iiif_print/text_extraction/page_ocr.rb
Labels: minor-ver

#209 Extracting ancestry identifier configurability
  lib/iiif_print/configuration.rb
  lib/iiif_print/lineage_service.rb
  spec/iiif_print/configuration_spec.rb
Labels: patch-ver

#208 Optimize identify -verbose
  lib/iiif_print/image_tool.rb
Labels: minor-ver

#211 Adding child_file_title_generator_function
  lib/iiif_print/configuration.rb
  lib/iiif_print/jobs/child_works_from_pdf_job.rb
  lib/iiif_print/split_pdfs/child_work_creation_from_pdf_service.rb
  spec/iiif_print/configuration_spec.rb
Labels: enhancement, minor-ver

#212 Raise an error on relationships job failure
  lib/iiif_print/jobs/create_relationships_job.rb
Labels: patch-ver

#213 Add guard to method
  app/services/iiif_print/manifest_builder_service_behavior.rb
Labels: patch-ver

#215 Add issue and PR templates to project
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ignore-for-release

#216 Renaming method for clarity for a confusing reality
  app/indexers/concerns/iiif_print/child_indexer.rb
  lib/iiif_print/lineage_service.rb
  spec/iiif_print/lineage_service_spec.rb
Labels: documentation, patch-ver

#217 Catalog to uv search
  README.md
  app/helpers/hyrax/iiif_helper.rb
  app/helpers/iiif_print/iiif_helper_decorator.rb
  app/models/concerns/iiif_print/solr/document.rb
  app/models/iiif_print/iiif_search_response_decorator.rb
  app/search_builders/concerns/iiif_print/highlight_search_params.rb
  app/views/catalog/_index_header_list_default.html.erb
  app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb
  lib/iiif_print/configuration.rb
  lib/iiif_print/engine.rb
  spec/iiif_print/catalog_search_builder_spec.rb
Labels: minor-ver

#221 Add configuration for child work attributes
  lib/iiif_print/configuration.rb
  lib/iiif_print/jobs/child_works_from_pdf_job.rb
  spec/iiif_print/configuration_spec.rb
Labels: minor-ver

#223 Omit syntax warnings from command
  lib/iiif_print/split_pdfs/pdf_image_extraction_service.rb
Labels: patch-ver

#225 revert change that introduced no matches found bug
  app/models/iiif_print/iiif_search_response_decorator.rb
Labels: patch-ver

#226 Sort canvas configuration
  app/services/iiif_print/manifest_builder_service_behavior.rb
  lib/iiif_print/configuration.rb
  spec/iiif_print/configuration_spec.rb
Labels: minor-ver

#227 Add configuration for OCR coordinate search
  lib/iiif_print/blacklight_iiif_search/annotation_decorator.rb
  lib/iiif_print/configuration.rb
  spec/iiif_print/configuration_spec.rb
Labels: minor-ver

#228 Add configuration for all_text indexing
  app/indexers/concerns/iiif_print/file_set_indexer.rb
  lib/iiif_print/configuration.rb
  spec/iiif_print/configuration_spec.rb
Labels: minor-ver

#229 Modify solr query for children
  app/services/iiif_print/manifest_builder_service_behavior.rb
Labels: patch-ver
