Repository notch8/iiif_print, pull requests merged in 2023-03, with the labels that each got.

#163 I160 release note setup
  .github/release.yml
Labels: ignore-for-release

#159 Skip blacklight_iiif_search:install solr changes
  README.md
  lib/generators/iiif_print/install_generator.rb
Labels: patch-ver

#165 Bail earlier
  app/actors/iiif_print/actors/file_set_actor_decorator.rb
  lib/iiif_print/split_pdfs/child_work_creation_from_pdf_service.rb
Labels: ignore-for-release

#168 failing tests should break the pipeline
  .github/workflows/build-lint-test-action.yaml
Labels: ignore-for-release

#169 Refactoring low-level classes for legibility
  lib/iiif_print/split_pdfs/pages_into_images_service.rb
  lib/iiif_print/split_pdfs/pdf_image_extraction_service.rb
Labels: patch-ver

#170 Adding Pages to PNGs splitter
  lib/iiif_print.rb
  lib/iiif_print/split_pdfs/base_splitter.rb
  lib/iiif_print/split_pdfs/pages_to_pngs_splitter.rb
  lib/iiif_print/split_pdfs/pages_to_tiffs_splitter.rb
  spec/iiif_print/split_pdfs/pages_into_images_service_spec.rb
  spec/iiif_print/split_pdfs/pages_to_pngs_splitter_spec.rb
  spec/iiif_print/split_pdfs/pages_to_tiffs_splitter_spec.rb
  spec/iiif_print_spec.rb
Labels: minor-ver

#172 Adding support for Hyrax
  app/services/iiif_print/manifest_builder_service_behavior.rb
Labels: minor-ver

#171 Add padding with zeros
  lib/iiif_print/jobs/child_works_from_pdf_job.rb
  spec/iiif_print/jobs/child_works_from_pdf_job_spec.rb
Labels: patch-ver

#174 Bug fixes due to refactoring
  lib/iiif_print/split_pdfs/base_splitter.rb
  lib/iiif_print/text_extraction/page_ocr.rb
Labels: patch-ver

#175 Allinson flex support
  app/services/iiif_print/manifest_builder_service_behavior.rb
  lib/iiif_print.rb
  lib/iiif_print/metadata.rb
  spec/iiif_print/metadata_spec.rb
Labels: minor-ver

#176 Update Redis gem
  spec/test_app_templates/lib/generators/test_app_generator.rb
Labels: patch-ver

#177 Refactor `#file_set_ids`
  app/presenters/iiif_print/work_show_presenter_decorator.rb
Labels: patch-ver

#178 Add jpg splitter and fix a bug
  lib/iiif_print/split_pdfs/base_splitter.rb
  lib/iiif_print/split_pdfs/pages_to_jpgs_splitter.rb
  spec/iiif_print/base_derivative_service_spec.rb
  spec/iiif_print/split_pdfs/base_splitter_spec.rb
  spec/iiif_print/split_pdfs/pages_to_jpgs_splitter_spec.rb
Labels: patch-ver

#180 Refactor another `#file_set_ids`
  app/presenters/iiif_print/iiif_manifest_presenter_factory_behavior.rb
Labels: patch-ver

#181 Narrowing list of default service plugins
  lib/iiif_print.rb
  spec/iiif_print_spec.rb
  spec/services/iiif_print/pluggable_derivative_service_spec.rb
Labels: enhancement, major-ver

#182 Add support for presentation v3 metadata
  app/services/iiif_print/manifest_builder_service_behavior.rb
  lib/iiif_print/metadata.rb
  spec/iiif_print/metadata_spec.rb
Labels: minor-ver

#186 Fix work show presenter
  app/presenters/iiif_print/work_show_presenter_decorator.rb
Labels: patch-ver

#189 non-images should create default Hyrax derivs
  lib/iiif_print/base_derivative_service.rb
  spec/iiif_print/base_derivative_service_spec.rb
Labels: patch-ver

#190 Metadata pain
  app/presenters/iiif_print/iiif_manifest_presenter_behavior.rb
  app/services/iiif_print/manifest_builder_service_behavior.rb
  lib/iiif_print.rb
Labels: minor-ver

#192 Add override for Hyrax
  app/presenters/iiif_print/iiif_manifest_presenter_behavior.rb
Labels: patch-ver

#191 I 187 search recent works
  README.md
  lib/iiif_print/homepage_search_builder.rb
Labels: minor-ver

#195 Remove empty strings from metadata pane
  lib/iiif_print.rb
  lib/iiif_print/metadata.rb
  spec/iiif_print/metadata_spec.rb
Labels: patch-ver

#197 Sequence child works by pdf & page
  lib/iiif_print/jobs/child_works_from_pdf_job.rb
Labels: ignore-for-release

#199 Ensuring version is set earlier in instantiation
  app/services/iiif_print/manifest_builder_service_behavior.rb
  lib/iiif_print/configuration.rb
  spec/iiif_print/configuration_spec.rb
  spec/services/iiif_print/manifest_builder_service_behavior_spec.rb
Labels: patch-ver

#200 Remove canvas sorting
  README.md
  app/services/iiif_print/manifest_builder_service_behavior.rb
  lib/generators/iiif_print/templates/config/initializers/iiif_print.rb
  lib/iiif_print/configuration.rb
  spec/iiif_print/configuration_spec.rb
Labels: minor-ver

#198 [i335] - port over serverless code from nnp
  README.md
  app/indexers/concerns/iiif_print/file_set_indexer.rb
  app/models/concerns/iiif_print/solr/document.rb
  app/presenters/iiif_print/iiif_manifest_presenter_behavior.rb
  lib/iiif_print/engine.rb
  spec/presenters/iiif_print/iiif_manifest_presenter_behavior_spec.rb
Labels: minor-ver

#207 I206 questioning authorities
  .github/workflows/build-lint-test-action.yaml
  Rakefile
  lib/iiif_print/metadata.rb
  spec/fixtures/authorities/licenses.yml
  spec/fixtures/authorities/rights_statements.yml
  spec/iiif_print/metadata_spec.rb
  tasks/copy_authorities_to_test_app.rake
  tasks/iiif_print_dev.rake
Labels: minor-ver
