Repository notch8/iiif_print, pull requests merged in 2023-05, with the labels that each got.

#230 Update GeneratedResourceSchema in childed_indexer
  app/indexers/concerns/iiif_print/child_indexer.rb
Labels: patch-ver

#231 Updating allinson flex features
  app/models/concerns/iiif_print/solr/document.rb
  app/presenters/iiif_print/iiif_manifest_presenter_behavior.rb
  lib/iiif_print.rb
  lib/iiif_print/configuration.rb
  lib/iiif_print/metadata.rb
  spec/iiif_print/configuration_spec.rb
  spec/iiif_print_spec.rb
Labels: minor-ver

#235 Don't show child metadata on the parent image
  app/services/iiif_print/manifest_builder_service_behavior.rb
  iiif_print.gemspec
Labels: patch-ver

#234 Search parent metadata instead of no match found
  app/models/iiif_print/iiif_search_decorator.rb
  lib/iiif_print/engine.rb
  spec/models/iiif_print/iiif_search_decorator_spec.rb
Labels: patch-ver

#236 Remove additional search terms from query string
  lib/iiif_print/blacklight_iiif_search/annotation_decorator.rb
  spec/iiif_print/blacklight_iiif_search/annotation_decorator_spec.rb
Labels: patch-ver

#237 [i387] - add default value to is_child property
  app/indexers/concerns/iiif_print/child_indexer.rb
  lib/iiif_print/configuration.rb
Labels: patch-ver

#240 🐛 Fix a `NilClass` error
  app/services/iiif_print/pluggable_derivative_service.rb
Labels: patch-ver

#241 🐛 Fix additional query terms removal
  lib/iiif_print/blacklight_iiif_search/annotation_decorator.rb
  spec/iiif_print/blacklight_iiif_search/annotation_decorator_spec.rb
Labels: patch-ver

#239 Rework relationships job
  .rubocop.yml
  lib/iiif_print.rb
  lib/iiif_print/engine.rb
  lib/iiif_print/jobs/create_relationships_job.rb
  spec/iiif_print/jobs/create_relationships_job_spec.rb
Labels: patch-ver

#246 🎬 Adding more files to the gitignore
  .gitignore
Labels: ignore-for-release

#247 ⚙️ Adding derivative-rodeo gem 🤠
  iiif_print.gemspec
Labels: ignore-for-release

#245 ♻️ Moving PDF file split guards into the service
  app/actors/iiif_print/actors/file_set_actor_decorator.rb
  lib/iiif_print/split_pdfs/child_work_creation_from_pdf_service.rb
Labels: ignore-for-release

#248 ⚙️ Remove `reform-rails` dependency
  iiif_print.gemspec
Labels: ignore-for-release

#249 ♻️ Preparing Splitter Service Swap for DerivativeRodeo
  app/services/iiif_print/pluggable_derivative_service.rb
  lib/iiif_print.rb
  lib/iiif_print/jobs/child_works_from_pdf_job.rb
  lib/iiif_print/split_pdfs/base_splitter.rb
  lib/iiif_print/split_pdfs/child_work_creation_from_pdf_service.rb
  spec/iiif_print/split_pdfs/base_splitter_spec.rb
Labels: ignore-for-release
