Repository notch8/iiif_print, pull requests merged in 2023-07, with the labels that each got.

#256 🐛 Restore PDF splitting functionality to main and bring in subsequent code changes
  app/actors/iiif_print/actors/file_set_actor_decorator.rb
  app/helpers/iiif_print/iiif_print_helper_behavior.rb
  app/helpers/iiif_print_helper.rb
  lib/generators/iiif_print/install_generator.rb
  lib/generators/iiif_print/templates/helpers/iiif_print_helper.rb
  lib/iiif_print/split_pdfs/child_work_creation_from_pdf_service.rb
Labels: patch-ver

#257 🐛 Fix typo `default` to `default_coords`
  lib/iiif_print/blacklight_iiif_search/annotation_decorator.rb
Labels: patch-ver

#258 🐛 Fix word count
  lib/iiif_print/text_extraction/hocr_reader.rb
  spec/iiif_print/text_extraction/hocr_reader_spec.rb
Labels: patch-ver

#252 🎁 Add ability to find pages split from a PDF
  app/services/iiif_print/derivative_rodeo_service.rb
  iiif_print.gemspec
  lib/iiif_print.rb
  spec/iiif_print/split_pdfs/derivative_rodeo_splitter_spec.rb
  spec/services/iiif_print/derivative_rodeo_service_spec.rb
Labels: ignore-for-release, Derivative Rodeo

#261 🐛 Fixing issue with misnamed constant and using variable before declared
  app/services/iiif_print/derivative_rodeo_service.rb
  lib/iiif_print/split_pdfs/derivative_rodeo_splitter.rb
Labels: patch-ver

#263 🎁 Add `AllinsonFlex` fields to solr queries
  app/search_builders/concerns/iiif_print/allinson_flex_fields.rb
  app/search_builders/concerns/iiif_print/iiif_search_builder_decorator.rb
  lib/iiif_print/catalog_search_builder.rb
  lib/iiif_print/engine.rb
Labels: minor-ver

#265 🐛 Adding more robust (albeit hacky) handling of ancestors
  app/services/iiif_print/derivative_rodeo_service.rb
  lib/iiif_print.rb
  lib/iiif_print/jobs/child_works_from_pdf_job.rb
Labels: patch-ver

#267 🎁 Make representative media alt text dynamic
  app/views/hyrax/base/_representative_media.html.erb
Labels: minor-ver

#268 🐛 Fix case insensitive query
  lib/iiif_print/blacklight_iiif_search/annotation_decorator.rb
Labels: patch-ver

#269 📚 Minor changes to improve legibility
  app/services/iiif_print/derivative_rodeo_service.rb
  iiif_print.gemspec
  lib/iiif_print/split_pdfs/derivative_rodeo_splitter.rb
Labels: minor-ver
