Repository notch8/iiif_print, pull requests merged in 2024-11, with the labels that each got.

#374 :bug: Fix image processing issue
  lib/iiif_print/image_tool.rb
Labels: bug, patch-ver

#375 i876 - Make memory, map, and disk limits in `im_identify` configurable
  lib/iiif_print/configuration.rb
  lib/iiif_print/image_tool.rb
Labels: minor-ver

#376 fix issue with iiif_print and s3 backed valkyrie file storage
  lib/iiif_print/split_pdfs/child_work_creation_from_pdf_service.rb
Labels: bug, patch-ver

#377 Fix lint errors
  app/jobs/iiif_print/jobs/child_works_from_pdf_job.rb
  lib/iiif_print/split_pdfs/child_work_creation_from_pdf_service.rb
Labels: ignore-for-release
